### ISSUE TITLE
Reshape error when training with one GPU

### ISSUE THREAD

**Issue by pender** [johnryh/Face_Embedding_GAN#3]
When trying to train with one GPU (Nvidia 1080Ti), I used the first line of `start_jobs_embedding_modified.sh`: except with GPU set to 1 instead of 4 as follows:

`python3 -W ignore train.py --GPU 1 --phase 1 --smooth 1 --size 32 --epoch 75 --batch_size 256 --lr 0.001 --n_critic 1 --use_embedding 1`

and I got the following error:

```
pender@penderforge:/mnt/brian/FaceGAN$ python3 -W ignore train.py --GPU 1 --phase 1 --smooth 1 --size 32 --epoch 75 --batch_size 256 --lr 0.001 --n_critic 1 --use_embedding 1
config
loading: [32, 32]
output: [8, 8]
prev_phase_iter: 0
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py:3632: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Tensor("Reshape:0", shape=(256, 8, 8, 3), dtype=float32) Tensor("Reshape_1:0", shape=(256, 8, 8, 1), dtype=float32)
Solver Configured

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1659, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot reshape a tensor with 524288 elements to shape [256,8192] (2097152 elements) for 'GAN/Generator/Mask_Embedding/Reshape' (op: 'Reshape') with input shapes: [256,8,8,32], [2] and with input tensors computed as partial shapes: input[1] = [256,8192].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 46, in <module>
    model = prog_w_gan(z, real_img, mask, phase = phase, LAMBDA=10)
  File "/mnt/brian/FaceGAN/network_utility.py", line 372, in __init__
    self.build_model(latent, real_img,  mask, phase=phase, LAMBDA=LAMBDA)
  File "/mnt/brian/FaceGAN/network_utility.py", line 401, in build_model
    fake_images, self.mask_features = generator(latent_split[gpu_id], phase_count=phase, num_base_features=g_max_num_features, num_feature_decay=0.5, alpha=self.g_alpha, mask=mask_split[gpu_id])
  File "/mnt/brian/FaceGAN/network_utility.py", line 237, in generator
    if mask is not None: mask_features, all_mask_features = mask_projection_path_more_features(mask)
  File "/mnt/brian/FaceGAN/network_utility.py", line 223, in mask_projection_path_more_features
    mask_features.append(dense(tf.reshape(mask_features[-1], [int(batch_size/num_gpus), target_size * target_size * mask_features[-1].shape[-1]]), embedding_latent_0_size, activation='linear', name='embedding_latent_0_size', gain=1))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 7179, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1823, in __init__
    control_input_ops)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1662, in _create_c_op
    raise ValueError(str(e))
ValueError: Cannot reshape a tensor with 524288 elements to shape [256,8192] (2097152 elements) for 'GAN/Generator/Mask_Embedding/Reshape' (op: 'Reshape') with input shapes: [256,8,8,32], [2] and with input tensors computed as partial shapes: input[1] = [256,8192].
```

I noticed that 524,288 is exactly one fourth of 2,097,152 so I tried quartering the batch size as follows but also got an error:

```
pender@penderforge:/mnt/brian/FaceGAN$ python3 -W ignore train.py --GPU 1 --phase 1 --smooth 1 --size 32 --epoch 75 --batch_size 64 --lr 0.001 --n_critic 1 --use_embedding 1
config
loading: [32, 32]
output: [8, 8]
prev_phase_iter: 0
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py:3632: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Tensor("Reshape:0", shape=(64, 8, 8, 3), dtype=float32) Tensor("Reshape_1:0", shape=(64, 8, 8, 1), dtype=float32)
Solver Configured

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1659, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot reshape a tensor with 131072 elements to shape [64,8192] (524288 elements) for 'GAN/Generator/Mask_Embedding/Reshape' (op: 'Reshape') with input shapes: [64,8,8,32], [2] and with input tensors computed as partial shapes: input[1] = [64,8192].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 46, in <module>
    model = prog_w_gan(z, real_img, mask, phase = phase, LAMBDA=10)
  File "/mnt/brian/FaceGAN/network_utility.py", line 372, in __init__
    self.build_model(latent, real_img,  mask, phase=phase, LAMBDA=LAMBDA)
  File "/mnt/brian/FaceGAN/network_utility.py", line 401, in build_model
    fake_images, self.mask_features = generator(latent_split[gpu_id], phase_count=phase, num_base_features=g_max_num_features, num_feature_decay=0.5, alpha=self.g_alpha, mask=mask_split[gpu_id])
  File "/mnt/brian/FaceGAN/network_utility.py", line 237, in generator
    if mask is not None: mask_features, all_mask_features = mask_projection_path_more_features(mask)
  File "/mnt/brian/FaceGAN/network_utility.py", line 223, in mask_projection_path_more_features
    mask_features.append(dense(tf.reshape(mask_features[-1], [int(batch_size/num_gpus), target_size * target_size * mask_features[-1].shape[-1]]), embedding_latent_0_size, activation='linear', name='embedding_latent_0_size', gain=1))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 7179, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1823, in __init__
    control_input_ops)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1662, in _create_c_op
    raise ValueError(str(e))
ValueError: Cannot reshape a tensor with 131072 elements to shape [64,8192] (524288 elements) for 'GAN/Generator/Mask_Embedding/Reshape' (op: 'Reshape') with input shapes: [64,8,8,32], [2] and with input tensors computed as partial shapes: input[1] = [64,8192].
```

Finally I tried the original line from `start_jobs_embedding_modified.sh` (even though I have only one GPU) and got the following:

```
pender@penderforge:/mnt/brian/FaceGAN$ python3 -W ignore train.py --GPU 4 --phase 1 --smooth 1 --size 32 --epoch 75 --batch_size 256 --lr 0.001 --n_critic 1 --use_embedding 1
config
loading: [32, 32]
output: [8, 8]
prev_phase_iter: 0
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py:3632: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Tensor("Reshape:0", shape=(256, 8, 8, 3), dtype=float32) Tensor("Reshape_1:0", shape=(256, 8, 8, 1), dtype=float32)
Solver Configured

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1659, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot reshape a tensor with 131072 elements to shape [64,8192] (524288 elements) for 'GAN/Generator/Mask_Embedding/Reshape' (op: 'Reshape') with input shapes: [64,8,8,32], [2] and with input tensors computed as partial shapes: input[1] = [64,8192].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 46, in <module>
    model = prog_w_gan(z, real_img, mask, phase = phase, LAMBDA=10)
  File "/mnt/brian/FaceGAN/network_utility.py", line 372, in __init__
    self.build_model(latent, real_img,  mask, phase=phase, LAMBDA=LAMBDA)
  File "/mnt/brian/FaceGAN/network_utility.py", line 401, in build_model
    fake_images, self.mask_features = generator(latent_split[gpu_id], phase_count=phase, num_base_features=g_max_num_features, num_feature_decay=0.5, alpha=self.g_alpha, mask=mask_split[gpu_id])
  File "/mnt/brian/FaceGAN/network_utility.py", line 237, in generator
    if mask is not None: mask_features, all_mask_features = mask_projection_path_more_features(mask)
  File "/mnt/brian/FaceGAN/network_utility.py", line 223, in mask_projection_path_more_features
    mask_features.append(dense(tf.reshape(mask_features[-1], [int(batch_size/num_gpus), target_size * target_size * mask_features[-1].shape[-1]]), embedding_latent_0_size, activation='linear', name='embedding_latent_0_size', gain=1))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 7179, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1823, in __init__
    control_input_ops)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1662, in _create_c_op
    raise ValueError(str(e))
ValueError: Cannot reshape a tensor with 131072 elements to shape [64,8192] (524288 elements) for 'GAN/Generator/Mask_Embedding/Reshape' (op: 'Reshape') with input shapes: [64,8,8,32], [2] and with input tensors computed as partial shapes: input[1] = [64,8192].
```

Is it possible to train with one GPU using this code? Thanks very much for any pointers or assistance!

**Comment by johnryh** [comment]
Hi, sorry for the buggy model implementation. The training is intended to start at phase 2 at the resolution of 16^2. The reason for omitting the first phase is that we observe the mask features from the short connection at this level is reducing the variation of model output.  I have fixed the training schedule and model loading logic. Please take a look and let me know if you have any further issue.

**Comment by pender** [comment]
Thank you very much for the help with this @johnryh (and thank you also for making your code available). It seems to be working for me. One other minor issue -- I had to change
```
data_folder = '/data'
```
to
```
data_folder = 'data'
```
[in config.py](https://github.com/johnryh/Face_Embedding_GAN/blob/master/config.py#L57) so it looks for the training data in the project folder instead of at the root level of the hard drive.

**Comment by pender** [comment]
The first two train commands from the shell script work, but the third gave me the following error:

```
pender@penderforge:/mnt/brian/FaceGAN$ python3 -W ignore train.py --GPU 1 --phase 3 --smooth 1 --size 16 --epoch 20 --batch_size 64 --lr 0.001 --n_critic 1 --use_embedding 1
config
loading: [64, 64]
output: [32, 32]
prev_phase_iter: 0
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py:3632: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Tensor("Reshape:0", shape=(64, 32, 32, 3), dtype=float32) Tensor("Reshape_1:0", shape=(64, 32, 32, 1), dtype=float32)
Solver Configured

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
var_list initiated
Discriminator Total parameters:20.774973M
Generator Total parameters:22.94107M
Total Total parameters:43.716043M
Session Initiated
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
***Phase3:  Phase_2 weights loaded***
  0%|                                                                                                                                      | 0/21875 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 256 values, but the requested shape has 4096
	 [[{{node Reshape_1}}]]
	 [[{{node IteratorGetNext}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 88, in <module>
    _, _, g_loss, d_loss, summary = sess.run([model.apply_d_grad, model.apply_g_grad, model.g_loss, model.d_loss, merged], feed_dict=smooth_factors)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 256 values, but the requested shape has 4096
	 [[node Reshape_1 (defined at train.py:43) ]]
	 [[node IteratorGetNext (defined at /mnt/brian/FaceGAN/Input_Pipeline_celeba.py:99) ]]

Caused by op 'Reshape_1', defined at:
  File "train.py", line 43, in <module>
    mask = tf.reshape(mask, [batch_size, output_img_h, output_img_w, 1])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 7179, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Input to reshape is a tensor with 256 values, but the requested shape has 4096
	 [[node Reshape_1 (defined at train.py:43) ]]
	 [[node IteratorGetNext (defined at /mnt/brian/FaceGAN/Input_Pipeline_celeba.py:99) ]]
```

**Comment by johnryh** [comment]
[loading_img_h/w in](https://github.com/johnryh/Face_Embedding_GAN/blob/fd94bcdc397b409b8c712204b366f85e84bbecce/config.py#L48) was not properly set. Let me know if this fixes your problem.

**Comment by pender** [comment]
Yes, seems to be working now. Thank you!

**Comment by pender** [comment]
When I get to the `#128` line in the shell script, I run into an error:

```
pender@penderforge:/mnt/brian/FaceGAN$ python3 -W ignore train.py --GPU 1 --phase 5 --smooth 1 --size 4 --epoch 10 --batch_size 32 --lr 0.0012 --n_critic 1 --use_embedding 1
config
loading: [4, 4]
output: [128, 128]
Traceback (most recent call last):
  File "train.py", line 20, in <module>
    from Input_Pipeline_celeba import *
  File "/mnt/brian/FaceGAN/Input_Pipeline_celeba.py", line 20, in <module>
    from config import *
  File "/mnt/brian/FaceGAN/config.py", line 67, in <module>
    train_tfrecord_path = train_file_dict[size]
KeyError: 4
```

Something is off with the sequence of size parameters in the config dictionary and in the shell script. The size parameters in the shell script start at 32, and then proceed to 16, 8, 4, and 2. But that means that the size of the training images get smaller as the training progress, and of course there are no training files for a size of 4.

Is the key supposed to be `4 * size**2` such that the config.py line would read
```
train_tfrecord_path = train_file_dict[4 * size**2]
```
instead of
```
train_tfrecord_path = train_file_dict[size]
```
? Then the sequence would be 8, 16, 32, 64, etc., which matches the keys in train_file_dict.

**Comment by johnryh** [comment]
It was loading_size = 1024/size.  For convenience I switched size to the literal size. Sorry for the confusion. Now it should be fixed
